force-app/main/default/objects/Site_Expenses__c/Site_Expenses__c.object-meta.xml
<CustomObject>
    <label>Site Expense</label>
    <nameField>
        <label>Name of Expense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Expenses__c/fields/Site_Visited__c.field-meta.xml
<CustomField>
    <fullName>Site_Visited__c</fullName>
    <label>Site Visited</label>
    <referenceTo>Site_Visits__c</referenceTo>
    <relationshipLabel>Site Expenses</relationshipLabel>
    <relationshipName>Site_Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Expenses__c/fields/Type_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Payment__c</fullName>
    <label>Type Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Diners Club</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visits__c/Site_Visits__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Visit Reason</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SiteVisitController.cls
public class SiteVisitController {
public List<Site_Expenses__c > selectedexpense{get;set;}    
public List<wrapexpense > ep {get;set;}
public List<site_Visits__c> sitelist{get;set;}
public List<Site_Expenses__c > ex{get;set;} 
public  Site_Expenses__c  exp {get;set;}

public  SiteVisitController(){
ep = new List<wrapexpense>();
exp = new Site_Expenses__c ();
ex= new List<Site_Expenses__c >();
//sitelist= [select id,Name from site__c];
Site_visits__c s = [select id,name,(select id,name,Amount__c,Type_Of_Payment__c
                              from Site_Expenses__r) 
                    from site_Visits__c
                    where id =: ApexPages.currentPage().getParameters().get('id')];
       ex = s.Site_Expenses__r;
    if(ep!=null){
 for(Site_Expenses__c  exp: ex){
 ep.add(new wrapexpense(exp));
 } 
 }  
 
}

public void saveu() {
    system.debug(ex);
        upsert ex;
    }


public void del() {
    for(wrapexpense wrobj : ep){
    if(wrobj.selected==true){
      delete wrobj.exs;
    } 
    
   
    }
    }



public  void saveex() {
 insert exp;
  if(ep!=null){
 
 ep.add(new wrapexpense(exp));
 } 
 exp = new Site_Expenses__c ();
  } 
   
   
public class wrapexpense {
        public Site_Expenses__c  exs {get; set;}
        public Boolean selected {get; set;}
       
 
        public wrapexpense (Site_Expenses__c  es) {
            exs = es;
            selected = false;
            
        }


}

   }